"""
Extract KS2 map terrain data for the /terrain web viewer, straight from map MPQs.

The published KS2 map re-bakes ONE terrain from a 22-map pool on each release. This
extractor works on any KS2 map archive (the live on-disk map, or a historical version
pulled from the Battle.net cache by scripts/harvest_terrains.py), so /terrain can offer
every terrain we've ever seen as a multi-map selector.

Per map it produces:
  - public/maps/<key>.png          the baked minimap (from Minimap.tga)
  - public/terrain/<key>.json      rock candidates + coord transform + packed pathing grid
And an index of all extracted maps:
  - data/terrain.json              { defaultMap, maps:[{key,name,nameZh,tileset,...}] }

Rock spawns are runtime-generated by Scripts/game/rocks.galaxy from the map's ramps:
the candidate pool is the set of regions named "Ramp<N>" (see gf_TerrainInit). Each game
shuffles them and places floor(rockProb * count), validated against pathing. We extract
the candidate pool + a passability grid + a cliff-level grid so the frontend simulator
(composables/useRockSimulator.ts) can reproduce the algorithm approximately.

Usage:  python scripts/build_terrain.py     (refresh the live map + rebuild index; run by build_all.py)
        python scripts/harvest_terrains.py  (one-time: pull every historical terrain from cache)
"""
import base64
import glob
import io
import json
import math
import os
import re
import struct
import xml.etree.ElementTree as ET

from PIL import Image

import lib_map as L

WIKI = r'D:\starcraft2\SanseKerriganSurvivalWiki'
DATA = os.path.join(WIKI, 'data')
PUBLIC_MAPS = os.path.join(WIKI, 'public', 'maps')
PUBLIC_TERRAIN = os.path.join(WIKI, 'public', 'terrain')

PLAYABLE_BORDER = 2.5     # Scripts/bootstrap.galaxy gv_mapBoundsRegionsMinimumBorder
CELLFLAGS_HEADER = 32     # t3CellFlags: 32-byte header then worldSize^2 bytes, 1/cell
# Only bits 0x01/0x02 are ever set. A cell of 0 is void/water/off-map; any flagged
# cell (0x01 buildable-ish and/or 0x02 pathable) is real ground. Masking != 0 gives a
# consistent land/void mask across ALL maps — on Mar Sara it equals the old 0x02 test
# (65408 cells) but on water maps (Lost Tides/Duck) it correctly keeps the islands,
# where a bare 0x02 test would drop nearly everything and break the simulator.
CELLFLAG_GROUND_MASK = 0x03
CLIFFLEVEL_HEADER = 32    # t3SyncCliffLevel: 32-byte header then worldSize^2 int16, 1/cell
# Adjacent walkable cells step by <=40 along ramps but jump 64/128/192 across cliff
# faces. <=48 => same ramp/plateau; a larger jump is a cliff only ramps bridge.
CLIFF_STEP = 48
CELLATTR_HEADER = 4       # CellAttribute_Pnp: 4-byte header then worldSize^2 bytes, 1/cell
DEFAULT_MAP_KEY = 'mar_sara_wastelands'

# The 22-map terrain pool (Scripts/*.galaxy ge_MapName_*). Each entry:
#   enum (as in ge_MapName_<ENUM>), CamelKey, snake_key, 中文名, tileset aliases
# tileset aliases match the token found in MapInfo when gv_map_CURRENT is unreadable.
POOL = [
    ('MAR_SARA_WASTELANDS',   'MarSaraWastelands',   'mar_sara_wastelands',   '玛尔萨拉废土',   ['marsara']),
    ('FOUR_SEASONS',          'FourSeasons',         'four_seasons',          '四季',           ['fourseasons']),
    ('LAST_SANCTUARY',        'LastSanctuary',       'last_sanctuary',        '最后的庇护所',   ['lastsanctuary']),
    ('SAND_FORT',             'SandFort',            'sand_fort',             '沙之要塞',       ['sandfort']),
    ('SNOW_PRISM',            'SnowPrism',           'snow_prism',            '雪之棱镜',       ['snowprism']),
    ('DUCK_MAP',              'DuckMap',             'duck_map',              '鸭子地图',       ['duckmap']),
    ('RUINS_OF_IMLADOON',     'RuinsOfImladoon',     'ruins_of_imladoon',     '伊姆拉顿废墟',   ['ruinsofimladoon', 'imladoon']),
    ('DEATH_VALLEY',          'DeathValley',         'death_valley',          '死亡谷',         ['deathvalley']),
    ('LOST_TIDES',            'LostTides',           'lost_tides',            '失落潮汐',       ['losttides', 'tidalfalls', 'tidalfalls']),
    ('CLASSIC',               'Classic',             'classic',               '经典',           ['classic']),
    ('VINTAGE_SHORES',        'VintageShores',       'vintage_shores',        '复古海岸',       ['vintageshores']),
    ('NO_HOPE',               'NoHope',              'no_hope',               '绝望之地',       ['nohope']),
    ('ADUNS_FORGOTTEN_TEMPLE','AdunsForgottenTemple','aduns_forgotten_temple','阿顿的失落神庙', ['adunsforgottentemple', 'mapsadunsforgottentemple']),
    ('CELESTIAL_SKYLINES',    'CelestialSkylines',   'celestial_skylines',    '天界天际线',     ['celestialskylines']),
    ('ZERUS_VOLCANOES',       'ZerusVolcanoes',      'zerus_volcanoes',       '泽鲁斯火山',     ['zerusvolcanoes', 'zerusvolcanos']),
    ('AIUR_FOUNTAINS',        'AiurFountains',       'aiur_fountains',        '艾尔喷泉',       ['aiurfountains']),
    ('CANAL',                 'Canal',               'canal',                 '运河',           ['canal']),
    ('GREENLAND',             'Greenland',           'greenland',             '绿地',           ['greenland']),
    ('HEART_OF_AMETHYST',     'HeartOfAmethyst',     'heart_of_amethyst',     '紫水晶之心',     ['heartofamethyst']),
    ('KALDIR_CLIFFS',         'KaldirCliffs',        'kaldir_cliffs',         '卡迪尔悬崖',     ['kaldircliffs']),
    ('MAZE',                  'Maze',                'maze',                  '迷宫',           ['maze']),
    ('THE_ISLAND',            'TheIsland',           'the_island',            '孤岛',           ['theisland']),
]
POOL_BY_ENUM = {e: p for p in POOL for e in [p[0]]}


def rock_model_for(camel_key, x, y):
    """Port of gf_MapRampRock (Scripts/init.galaxy). Position only matters for FourSeasons."""
    table = {
        'Classic': 'CommonTerrainDebris4x4',
        'ZerusVolcanoes': 'ZerusVolcanoesRock',
        'RuinsOfImladoon': 'ZerusVolcanoesRock',
        'KaldirCliffs': 'CommonTerrainIce4x4',
        'AiurFountains': 'CommonTerrainIce4x4',
        'LostTides': 'CommonRockBlackStones',
        'DeathValley': 'ZerusVolcanoesRock',
    }
    if camel_key == 'FourSeasons':
        if x > 128.0 and y < 128.0:
            return 'CommonTerrainIce4x4'
        if x < 128.0 and y > 128.0:
            return 'CommonTerrainRockMossyRock'
        return 'ZerusVolcanoesRock'
    return table.get(camel_key, 'CommonRockBlackStones')


def read_tileset_token(archive):
    """First plausible tileset token from MapInfo (used to name maps whose
    gv_map_CURRENT is unreadable). e.g. 'MarSaraEx1', 'FourSeasonsTerrainType251'."""
    try:
        mi = archive.read_file('MapInfo') or b''
    except Exception:
        return ''
    skip = {b'BattleNet', b'Layout', b'LoadingScreen', b'SC2Layout', b'KerriganLoadingScreen', b'Dark'}
    for t in re.findall(rb'[A-Z][A-Za-z0-9]{4,}', mi):
        if t not in skip:
            return t.decode('ascii', 'replace')
    return ''


def read_map_enum(archive):
    """gv_map_CURRENT = ge_MapName_<ENUM> from bootstrap.galaxy (authoritative)."""
    for fn in ('Scripts\\bootstrap.galaxy', 'Scripts/bootstrap.galaxy'):
        try:
            b = archive.read_file(fn)
        except Exception:
            b = None
        if b:
            m = re.search(rb'gv_map_CURRENT\s*=\s*ge_MapName_(\w+)', b)
            if m:
                return m.group(1).decode('ascii')
    return None


def resolve_identity(archive):
    """(camel, snake, zh, tileset) for a KS2 map archive.

    Prefer gv_map_CURRENT (exact pool enum); fall back to the MapInfo tileset token
    matched against pool aliases; else a slugified tileset with '未知地形' label."""
    tileset = read_tileset_token(archive)
    enum = read_map_enum(archive)
    if enum and enum in POOL_BY_ENUM:
        e, camel, snake, zh, _ = POOL_BY_ENUM[enum]
        return camel, snake, zh, tileset
    # fall back to tileset alias matching
    norm = re.sub(r'[^a-z]', '', tileset.lower())
    for e, camel, snake, zh, aliases in POOL:
        for a in aliases:
            if norm.startswith(a) or a in norm:
                return camel, snake, zh, tileset
    # unknown terrain: slug from tileset, keep it visible rather than dropping it
    slug = re.sub(r'[^a-z0-9]+', '_', (tileset or 'unknown').lower()).strip('_') or 'unknown'
    camel = ''.join(w.capitalize() for w in slug.split('_'))
    return camel, slug, f'未知地形（{tileset or "?"}）', tileset


def parse_rock_candidates(archive):
    """All 'Ramp<N>' rect regions, center = quad midpoint, ordered ascending by N
    (matches how gf_TerrainInit compacts gv_terrainRockRegions)."""
    xml = archive.read_file('Regions').decode('utf-8-sig', 'replace')
    root = ET.fromstring(xml)
    out = []
    for region in root.findall('region'):
        name_el = region.find('name')
        name = name_el.get('value') if name_el is not None else ''
        m = re.fullmatch(r'Ramp(\d+)', name or '')
        if not m:
            continue
        quad = region.find('./shape/quad')
        if quad is None:
            continue
        minx, miny, maxx, maxy = (float(v) for v in quad.get('value').split(','))
        out.append({
            'n': int(m.group(1)),
            'x': round((minx + maxx) / 2, 4),
            'y': round((miny + maxy) / 2, 4),
        })
    out.sort(key=lambda r: r['n'])
    return out


def _world_size(archive):
    """Playable terrain is square; derive its cell dimension from t3CellFlags length."""
    data = archive.read_file('t3CellFlags')
    n = len(data) - CELLFLAGS_HEADER
    size = int(round(math.sqrt(n)))
    if size * size != n:
        raise ValueError(f't3CellFlags payload {n} is not a perfect square')
    return size, data


def pack_pathing(archive, world_size, cellflags):
    """t3CellFlags -> worldSize^2 land/void bitfield (flags & 0x03), row-major, base64.
    Row 0 = world y=0 (bottom); frontend maps world->pixel with a Y flip."""
    cells = cellflags[CELLFLAGS_HEADER:CELLFLAGS_HEADER + world_size * world_size]
    bits = bytearray((world_size * world_size + 7) // 8)
    passable = 0
    for i, b in enumerate(cells):
        if b & CELLFLAG_GROUND_MASK:
            bits[i >> 3] |= (1 << (i & 7))
            passable += 1
    return base64.b64encode(bytes(bits)).decode('ascii'), passable


def pack_cliff(archive, world_size):
    """t3SyncCliffLevel -> worldSize^2 cliff levels as uint16 LE (row-major, base64).
    Levels reach 576 on high-cliff maps (Maze/DeathValley), so a byte would clip and
    collapse plateaus into one level, defeating CLIFF_STEP. uint16 keeps raw resolution.
    Frontend blocks adjacency where the level difference exceeds CLIFF_STEP."""
    data = archive.read_file('t3SyncCliffLevel')
    n = world_size * world_size
    levels = struct.unpack_from(f'<{n}h', data, CLIFFLEVEL_HEADER)
    lo, hi = min(levels), max(levels)
    packed = struct.pack(f'<{n}H', *(min(65535, max(0, v)) for v in levels))
    return base64.b64encode(packed).decode('ascii'), lo, hi


def pack_blockers(archive, world_size):
    """Permanent, non-terrain pathing blockers -> worldSize^2 bitfield (row-major, base64).

    t3CellFlags only carries terrain walkability; it does NOT include doodads or placed
    units, whose pathing footprints the game stamps at load time. Without them the rock
    simulator sees empty ground where trees / watchtowers actually block, and keeps rocks
    the real game would reject -> phantom dead zones (reported on multi-level cliffs).

    Two authoritative sources, same row order as t3CellFlags (world y=0 = row 0, no flip):
      - CellAttribute_Pnp: 4B header + W*W sub-cell block masks; nonzero => doodad blocks
        this cell. The editor already baked exact footprints here (no radius guessing).
      - Objects (XML <PlacedObjects>): CommonXelNagaTower ObjectUnits are permanent neutral
        structures (2x2 Footprint2x2Contour), not in Pnp; rasterize a 2x2 footprint at
        floor(x-1..x), floor(y-1..y) around each tower center.

    Missing files (older/odd archives) degrade to an empty layer rather than failing."""
    n = world_size * world_size
    blocked = bytearray((n + 7) // 8)
    count = 0

    def mark(cx, cy):
        nonlocal count
        if 0 <= cx < world_size and 0 <= cy < world_size:
            i = cy * world_size + cx
            if not (blocked[i >> 3] & (1 << (i & 7))):
                blocked[i >> 3] |= (1 << (i & 7))
                count += 1

    # doodad / decoration footprints from the editor's no-pathing overlay
    try:
        pnp = archive.read_file('CellAttribute_Pnp')
        body = pnp[CELLATTR_HEADER:CELLATTR_HEADER + n]
        for i, b in enumerate(body):
            if b:
                mark(i % world_size, i // world_size)
    except Exception:
        pass

    # permanent placed units (watchtowers) — runtime footprints, absent from Pnp
    try:
        objs = ET.fromstring(archive.read_file('Objects').decode('utf-8', 'replace'))
        for e in objs:
            if e.get('UnitType') != 'CommonXelNagaTower':
                continue
            pos = e.get('Position')
            if not pos:
                continue
            x, y = (float(v) for v in pos.split(',')[:2])
            cx, cy = int(x), int(y)
            for dx in (-1, 0):
                for dy in (-1, 0):
                    mark(cx + dx, cy + dy)
    except Exception:
        pass

    return base64.b64encode(bytes(blocked)).decode('ascii'), count


def save_minimap(archive, key):
    """Minimap.tga -> public/maps/<key>.png. Pillow normalizes TGA orientation to
    top-left origin, so row 0 = top = world y=max."""
    tga = archive.read_file('Minimap.tga')
    img = Image.open(io.BytesIO(tga)).convert('RGB')
    os.makedirs(PUBLIC_MAPS, exist_ok=True)
    path = os.path.join(PUBLIC_MAPS, f'{key}.png')
    img.save(path, 'PNG', optimize=True)
    return f'/maps/{key}.png', img.size


def extract_map(archive, key, camel, snake, zh, tileset, date=None):
    """Full per-map extraction -> writes public/terrain/<key>.json + public/maps/<key>.png.
    Returns the lightweight index entry."""
    world_size, cellflags = _world_size(archive)
    candidates = parse_rock_candidates(archive)
    if not candidates:
        raise ValueError(f'{key}: no Ramp regions found')

    minimap_path, size = save_minimap(archive, key)
    px_per_cell = round(size[0] / world_size, 6)

    bits_b64, passable = pack_pathing(archive, world_size, cellflags)
    cliff_b64, clo, chi = pack_cliff(archive, world_size)
    block_b64, blockers = pack_blockers(archive, world_size)

    uniform_model = rock_model_for(camel, 0, 0)
    per_pos = {rock_model_for(camel, c['x'], c['y']) for c in candidates}
    rock_model = uniform_model if len(per_pos) == 1 else None
    if rock_model is None:
        for c in candidates:
            c['model'] = rock_model_for(camel, c['x'], c['y'])

    border = PLAYABLE_BORDER
    full = {
        'key': key,
        'map': camel,
        'nameZh': zh,
        'tileset': tileset,
        'worldSize': world_size,
        'minimap': {'path': minimap_path, 'pxPerCell': px_per_cell, 'originY': 'bottom'},
        'playableBounds': [border, border, world_size - border, world_size - border],
        'rockModel': rock_model,
        'rockProbDefault': 0.5,
        'rockCandidates': candidates,
        'pathing': {
            'w': world_size, 'h': world_size,
            'bits': bits_b64,          # walkable ground (t3CellFlags bit 0x02)
            'cliff': cliff_b64,        # cliff level per cell (t3SyncCliffLevel)
            'cliffStep': CLIFF_STEP,   # adjacency blocked if |Δlevel| > cliffStep
            'block': block_b64,        # permanent non-terrain blockers (doodads + watchtowers)
        },
    }
    if date:
        full['date'] = date

    os.makedirs(PUBLIC_TERRAIN, exist_ok=True)
    with open(os.path.join(PUBLIC_TERRAIN, f'{key}.json'), 'w', encoding='utf-8') as f:
        json.dump(full, f, ensure_ascii=False, separators=(',', ':'))

    print(f'  {key}: world {world_size}, {len(candidates)} ramps, '
          f'{passable} passable, {blockers} blockers, cliff {clo}..{chi}, minimap {size[0]}x{size[1]}')
    return {
        'key': key, 'map': camel, 'nameZh': zh, 'tileset': tileset,
        'worldSize': world_size, 'minimap': minimap_path,
        'rockModel': rock_model, 'rockProbDefault': 0.5,
        'candidateCount': len(candidates), 'date': date,
    }


def build_index():
    """Assemble data/terrain.json from every public/terrain/<key>.json on disk, so
    the live-map refresh and the one-time cache harvest can each just drop files."""
    entries = []
    for path in sorted(glob.glob(os.path.join(PUBLIC_TERRAIN, '*.json'))):
        with open(path, encoding='utf-8') as f:
            m = json.load(f)
        entries.append({
            'key': m['key'], 'map': m['map'], 'nameZh': m.get('nameZh', m['map']),
            'tileset': m.get('tileset', ''), 'worldSize': m['worldSize'],
            'minimap': m['minimap']['path'], 'rockModel': m.get('rockModel'),
            'rockProbDefault': m.get('rockProbDefault', 0.5),
            'candidateCount': len(m.get('rockCandidates', [])), 'date': m.get('date'),
        })
    # newest first; the live default map pinned to the front
    entries.sort(key=lambda e: (e['key'] != DEFAULT_MAP_KEY, e.get('date') or '', e['key']),
                 reverse=False)
    entries.sort(key=lambda e: (e['key'] != DEFAULT_MAP_KEY, -(_date_num(e.get('date')))))
    out = {'defaultMap': DEFAULT_MAP_KEY if any(e['key'] == DEFAULT_MAP_KEY for e in entries)
           else (entries[0]['key'] if entries else None),
           'maps': entries}
    os.makedirs(DATA, exist_ok=True)
    with open(os.path.join(DATA, 'terrain.json'), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f'index: {len(entries)} maps -> data/terrain.json (default {out["defaultMap"]})')
    return out


def _date_num(d):
    if not d:
        return 0
    try:
        return int(d.replace('-', ''))
    except Exception:
        return 0


def main():
    """Refresh the live on-disk map and rebuild the index (used by build_all.py)."""
    archive = L.open_map()
    camel, snake, zh, tileset = resolve_identity(archive)
    print(f'live map: {camel} ({snake}) tileset={tileset}')
    # the live map always owns the canonical (undated) key for its terrain
    extract_map(archive, snake, camel, snake, zh, tileset, date=None)
    build_index()


if __name__ == '__main__':
    main()
