"""
Extract KS2 map terrain data for the /terrain web viewer, straight from the map MPQ
via lib_map (no dependency on a manual extraction dir).

Produces:
  - data/terrain.json                 rock candidates + coord transform + packed pathing grid
  - public/maps/<mapkey>.png          the baked minimap (from Minimap.tga)

Rock spawns are runtime-generated by Scripts/game/rocks.galaxy from the map's ramps:
the candidate pool is the set of regions named "Ramp<N>" (see gf_TerrainInit / gf_TerrainRampGet
in Scripts/init.galaxy). Each game shuffles them and places floor(rockProb * count), validated
against pathing. We extract the candidate pool + a passability grid so the frontend simulator
(composables/useRockSimulator.ts) can reproduce the algorithm approximately.

The active terrain is baked into this single .SC2Map; gv_map_CURRENT (Scripts/bootstrap.galaxy)
only selects logic/rock-model. Output is keyed by map name so future variants accumulate.

Usage:  python scripts/build_terrain.py     (run from the Wiki root; also run by build_all.py)
"""
import base64
import io
import json
import os
import re
import xml.etree.ElementTree as ET

from PIL import Image

import lib_map as L

WIKI = r'D:\starcraft2\SanseKerriganSurvivalWiki'
DATA = os.path.join(WIKI, 'data')
PUBLIC_MAPS = os.path.join(WIKI, 'public', 'maps')

WORLD_SIZE = 256          # playable terrain is 256x256 cells (t3Terrain dim 257x257 vertices)
PX_PER_CELL = 4           # Minimap.tga is 1024x1024 -> 4 px per cell
PLAYABLE_BOUNDS = [2.5, 2.5, 253.5, 253.5]   # Scripts/bootstrap.galaxy gv_mapBoundsRegionsMinimumBorder
CELLFLAGS_HEADER = 32     # t3CellFlags: 32-byte header then 256*256 bytes, 1/cell
CELLFLAG_PATHABLE_BIT = 0x02
CLIFFLEVEL_HEADER = 32    # t3SyncCliffLevel: 32-byte header then 256*256 int16, 1/cell
# Adjacent walkable cells step by <=40 along ramps but jump 64/128/192 across cliff
# faces (verified from the map's cliff-diff histogram). <=48 => same ramp/plateau;
# a larger jump is a cliff you can't walk across (only ramps bridge plateaus).
CLIFF_STEP = 48


def _enum_to_key(enum_name):
    """ge_MapName_MAR_SARA_WASTELANDS -> ('MarSaraWastelands', 'mar_sara_wastelands')."""
    words = enum_name.split('_')
    camel = ''.join(w.capitalize() for w in words)
    snake = enum_name.lower()
    return camel, snake


def detect_current_map(archive):
    """Read the single assignment of gv_map_CURRENT from bootstrap.galaxy."""
    try:
        txt = archive.read_file('Scripts\\bootstrap.galaxy').decode('utf-8', 'replace')
    except Exception:
        txt = ''
    m = re.search(r'gv_map_CURRENT\s*=\s*ge_MapName_(\w+)\s*;', txt)
    enum = m.group(1) if m else 'UNKNOWN'
    return _enum_to_key(enum)


def rock_model_for(camel_key, x, y):
    """Port of gf_MapRampRock (Scripts/init.galaxy). Position only matters for FourSeasons."""
    table = {
        'Classic': 'CommonTerrainDebris4x4',
        'ZerusVolcanoes': 'ZerusVolcanoesRock',
        'RuinsOfImladoon': 'ZerusVolcanoesRock',
        'KaldirCliffs': 'CommonTerrainIce4x4',
        'AiurFountains': 'CommonTerrainIce4x4',
        'LostTides': 'CommonRockBlackStones',
        'DeathValley': 'ZerusVolcanoesRock',
    }
    if camel_key == 'FourSeasons':
        if x > 128.0 and y < 128.0:
            return 'CommonTerrainIce4x4'
        if x < 128.0 and y > 128.0:
            return 'CommonTerrainRockMossyRock'
        return 'ZerusVolcanoesRock'
    return table.get(camel_key, 'CommonRockBlackStones')


def parse_rock_candidates(archive):
    """All 'Ramp<N>' rect regions, center = quad midpoint, ordered ascending by N
    (matches how gf_TerrainInit compacts gv_terrainRockRegions)."""
    xml = archive.read_file('Regions').decode('utf-8-sig', 'replace')
    root = ET.fromstring(xml)
    out = []
    for region in root.findall('region'):
        name_el = region.find('name')
        name = name_el.get('value') if name_el is not None else ''
        m = re.fullmatch(r'Ramp(\d+)', name or '')
        if not m:
            continue
        quad = region.find('./shape/quad')
        if quad is None:
            continue
        minx, miny, maxx, maxy = (float(v) for v in quad.get('value').split(','))
        out.append({
            'n': int(m.group(1)),
            'x': round((minx + maxx) / 2, 4),
            'y': round((miny + maxy) / 2, 4),
        })
    out.sort(key=lambda r: r['n'])
    return out


def pack_pathing(archive):
    """t3CellFlags -> 256x256 passability bitfield (bit0x02), row-major, base64.
    Row 0 = world y=0 (bottom); frontend maps world->pixel with a Y flip."""
    data = archive.read_file('t3CellFlags')
    cells = data[CELLFLAGS_HEADER:CELLFLAGS_HEADER + WORLD_SIZE * WORLD_SIZE]
    if len(cells) != WORLD_SIZE * WORLD_SIZE:
        raise ValueError(f't3CellFlags data size {len(cells)} != {WORLD_SIZE * WORLD_SIZE}')
    bits = bytearray((WORLD_SIZE * WORLD_SIZE + 7) // 8)
    passable = 0
    for i, b in enumerate(cells):
        if b & CELLFLAG_PATHABLE_BIT:
            bits[i >> 3] |= (1 << (i & 7))
            passable += 1
    return base64.b64encode(bytes(bits)).decode('ascii'), passable


def pack_cliff(archive):
    """t3SyncCliffLevel -> 256x256 cliff-level bytes (row-major, base64).
    Levels are 0..192 (fit a byte); frontend blocks adjacency where the level
    difference exceeds CLIFF_STEP (a cliff face, only ramps bridge plateaus)."""
    import struct
    data = archive.read_file('t3SyncCliffLevel')
    n = WORLD_SIZE * WORLD_SIZE
    levels = struct.unpack_from(f'<{n}h', data, CLIFFLEVEL_HEADER)
    lo, hi = min(levels), max(levels)
    if lo < 0 or hi > 255:
        raise ValueError(f'cliff level out of byte range: {lo}..{hi}')
    return base64.b64encode(bytes(levels)).decode('ascii'), lo, hi


def save_minimap(archive, snake_key):
    """Minimap.tga -> public/maps/<snake>.png. Pillow normalizes TGA orientation to
    top-left origin, so row 0 = top = world y=256."""
    tga = archive.read_file('Minimap.tga')
    img = Image.open(io.BytesIO(tga)).convert('RGB')
    os.makedirs(PUBLIC_MAPS, exist_ok=True)
    path = os.path.join(PUBLIC_MAPS, f'{snake_key}.png')
    img.save(path, 'PNG', optimize=True)
    return f'/maps/{snake_key}.png', img.size


def main():
    archive = L.open_map()
    camel, snake = detect_current_map(archive)
    print(f'current map: {camel} ({snake})')

    candidates = parse_rock_candidates(archive)
    print(f'rock candidates: {len(candidates)} (Ramp regions)')
    xs = [c['x'] for c in candidates]
    ys = [c['y'] for c in candidates]
    assert candidates, 'no Ramp regions found'
    assert all(0 <= v <= WORLD_SIZE for v in xs + ys), 'candidate out of 0..256'

    minimap_path, size = save_minimap(archive, snake)
    print(f'minimap: {minimap_path} {size[0]}x{size[1]}')

    bits_b64, passable = pack_pathing(archive)
    print(f'pathing: {passable}/{WORLD_SIZE*WORLD_SIZE} cells passable (bit 0x02)')

    cliff_b64, clo, chi = pack_cliff(archive)
    print(f'cliff levels: {clo}..{chi} (step<= {CLIFF_STEP} bridges ramps)')

    # Mar Sara (and most) use a uniform rock model; FourSeasons varies by position.
    uniform_model = rock_model_for(camel, 0, 0)
    per_pos = {rock_model_for(camel, c['x'], c['y']) for c in candidates}
    rock_model = uniform_model if len(per_pos) == 1 else None

    out = {
        'map': camel,
        'mapKey': snake,
        'tileset': 'MarSaraEx1',
        'worldSize': WORLD_SIZE,
        'minimap': {'path': minimap_path, 'pxPerCell': PX_PER_CELL, 'originY': 'bottom'},
        'playableBounds': PLAYABLE_BOUNDS,
        'rockModel': rock_model,
        'rockProbDefault': 0.5,
        'rockCandidates': candidates,
        'pathing': {
            'w': WORLD_SIZE, 'h': WORLD_SIZE,
            'bits': bits_b64,          # walkable ground (t3CellFlags bit 0x02)
            'cliff': cliff_b64,        # cliff level per cell (t3SyncCliffLevel)
            'cliffStep': CLIFF_STEP,   # adjacency blocked if |Δlevel| > cliffStep
        },
    }
    if rock_model is None:  # position-dependent model (e.g. FourSeasons)
        for c in candidates:
            c['model'] = rock_model_for(camel, c['x'], c['y'])

    os.makedirs(DATA, exist_ok=True)
    path = os.path.join(DATA, 'terrain.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f'wrote {path}')


if __name__ == '__main__':
    main()
